server:
  port: 8080

#database  config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tlias_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

  servlet:
    multipart:
      # 上传文件最大限制（默认10M）
      max-request-size: 50MB
      # 单个文件最大限制（默认1M）
      max-file-size: 10MB

#mybatis  config
mybatis-plus:
  # mapper文件位置
  mapper-locations: classpath:mappers/*.xml
  # 实体类包名
  type-aliases-package: com.itheima.d01_tlias_manager.pojo
  # 全局配置
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名转换
    map-underscore-to-camel-case: true

  # mybatis-plus 全局配置
  global-config:
    db-config:
      id-type: auto             # 全局id类型为自增长
      update-strategy: not_null # 更新策略：只更新非空字段

#spring transaction  log
logging:
  level:
    org.springframework.transaction: debug

aliyun:
  oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketName: java-muggle666
      region: cn-beijing




